name: Compile/Test/Publish

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
          scope: '@gammaswap'
      - run: pnpm install
      - run: pnpm run build
      - name: Publish Package
        if: "(contains(github.event.head_commit.message, 'publish package'))"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
