name: Compile/Test

on:
  push:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  compile-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4.4.0

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          registry-url: https://npm.pkg.github.com/
          scope: "@gammaswap"

      - run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm run build

      - run: pnpm run test
